### ISSUE TITLE
Pass current mission doesn't work with Wear Flowers in Your Hair

### ISSUE THREAD

**Issue by mariuszkurek** [gta-chaos-mod/ASI-script#14]
I was doing Wear Flowers in Your Hair (got teleported home, how funny) and while the objective was to go to the hospital, I got Pass Current Mission effect. However, it did absolutely nothing.

**Comment by Lordmau5** [comment]
`Pass Current Mission` works is utilizing a left-over debug key check in the game from the PS2-era.
Some missions don't have that debug check in place so they won't be passed (another example would be Mike Toreno).

I'm thinking of modifying the `data/script/main.scm` to include those checks in the remaining missions, but it's not something I have the highest priority right now

**Comment by Lordmau5** [comment]
Alright, so got a status update on this!

Apparently it's possible for me to implement a custom `Pass Current Mission` functionality for every single mission in the game :)

This would also fix the following:
- During the races, instead of teleporting to the next checkpoint, it'd pass the race
- During other missions it'd finish them properly, too

Problems I could face with this:
- Branching mission lines, such as the Catalina missions - How would I handle the mission finish for those?
