### ISSUE TITLE
pass current mission (real) not working

### ISSUE THREAD

**Issue by thegithubuser1** [gta-chaos-mod/ASI-script#47]
For some reason, the actual pass current mission cheat doesnt make me pass the mission. the only one that works is the fake one. any reason why?

**Comment by Lordmau5** [comment]
Absolutely no idea, no.
But I also won't be looking into it up until v2.0 is released as that has a complete code overhaul anyway and during testing it was working perfectly fine.

Also, do keep in mind that certain missions simply **cannot be passed** due to how their mission scripts are working.

I have to make a list of those so people (and me including) will know which ones will and which ones won't pass :P
