### ISSUE TITLE
Game crashes when started

### ISSUE THREAD

**Issue by nasue123** [gta-chaos-mod/ASI-script#60]

**Comment by Lordmau5** [comment]
_"No description provided."_

Did you *just* install the mod?
Were you playing with it before and it autosaved?
What *exactly* happens when you are starting the game?
Do you even see the logo come up before you would be getting into the main menu?

My assumption is that it autosaved some corrupted data and thus can't load anymore.

You can try holding Left CTRL whilst the game is starting up (hold it when you see the logo come up).
If that works, then it's the autosave.

**Comment by nasue123** [comment]
I made a mistake instaling it, sorry! The mod is fully working now, my game
was just closing just after i opened it, but it's solved.

**Comment by Lordmau5** [comment]
Glad you got it resolved! 😁
